spring.application.name=transaction-service

spring.datasource.url=jdbc:mysql://localhost:3311/nexpay_transaction
spring.datasource.username=nexpay
spring.datasource.password=nexpay123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8084